#! /bin/bash

cp ./.bash_profile /home/$(whoami)/
cp ./.vimrc /home/$(whoami)/
cp ./.gitconfig /home/$(whoami)/

ln -s ~/.bash_profile ~/.bashrc

echo "run '. ~/.bash_profile' for changes to take effect"
